openapi: 3.0.0
info:
  title: Football Competition API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Local server

paths:
  /competitions:
    get:
      summary: Get a list of competitions
      description: Retrieve a paginated list of competitions.
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: true
          schema:
            type: integer
        - name: pageSize
          in: query
          description: Number of items per page
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of competitions.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Competition'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /teams:
    get:
      summary: Get a list of teams
      description: Retrieve a paginated list of teams, optionally filtered by team name.
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: true
          schema:
            type: integer
        - name: pageSize
          in: query
          description: Number of items per page
          required: true
          schema:
            type: integer
        - name: teamName
          in: query
          description: Filter teams by name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: A list of teams.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Team'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new team
      description: Create a new football team with a name and slogan.
      requestBody:
        description: Team object to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeamInput'
      responses:
        '201':
          description: Team created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Team'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Competition:
      type: object
      properties:
        name:
          type: string
        location:
          type: string

    Team:
      type: object
      properties:
        name:
          type: string
        slogan:
          type: string
        competitions:
          type: array
          items:
            $ref: '#/components/schemas/Competition'
        players:
          type: array
          items:
            $ref: '#/components/schemas/Player'

    TeamInput:
      type: object
      properties:
        name:
          type: string
        slogan:
          type: string
      required:
        - name
        - slogan

    Player:
      type: object
      properties:
        name:
          type: string
        number:
          type: integer
        dominantFoot:
          type: string
          enum:
            - Left
            - Right

    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
